//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

use crate::enums::{OrderSide, OrderStatus, RejectReason};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "orders")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub symbol: String,
    pub side: OrderSide,
    #[sea_orm(column_type = "Decimal(Some((30, 10)))")]
    pub quantity: BigDecimal,
    #[sea_orm(column_type = "Decimal(Some((30, 10)))", nullable)]
    pub price: Option<BigDecimal>,
    pub status: OrderStatus,
    pub reject_reason: Option<RejectReason>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
