//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "OrderSide")]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum OrderSide {
    #[sea_orm(string_value = "BUY")]
    Buy,
    #[sea_orm(string_value = "SELL")]
    Sell,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "OrderStatus")]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum OrderStatus {
    #[sea_orm(string_value = "CREATED")]
    Created,
    #[sea_orm(string_value = "EXECUTED")]
    Executed,
    #[sea_orm(string_value = "REJECTED")]
    Rejected,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "RejectReason")]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum RejectReason {
    #[sea_orm(string_value = "INSUFFICIENT_CASH")]
    InsufficientCash,
    #[sea_orm(string_value = "INSUFFICIENT_ASSET")]
    InsufficientAsset,
    #[sea_orm(string_value = "MARKET_SERVICE_UNAVAILABLE")]
    MarketServiceUnavailable,
    #[sea_orm(string_value = "INVALID_SYMBOL")]
    InvalidSymbol,
    #[sea_orm(string_value = "INVALID_QUANTITY")]
    InvalidQuantity,
}
