//! Hand-written parsing for the enums in [`crate::enums`].
//!
//! Kept separate from `enums.rs` because that file is regenerated by
//! sea-orm-codegen, which would overwrite anything added there.

use std::str::FromStr;

use crate::enums::OrderSide;

/// Parses a user-supplied order side, accepting `BUY`/`SELL` case-insensitively
/// and tolerating surrounding whitespace. Any other value is rejected.
impl FromStr for OrderSide {
    type Err = ();

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.trim().to_uppercase().as_str() {
            "BUY" => Ok(Self::Buy),
            "SELL" => Ok(Self::Sell),
            _ => Err(()),
        }
    }
}
